version: '3'
services:
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq
  client:
    # hostname: rabbitmq
    build: .
    command: yarn start
    restart: on-failure
    restart: always
    networks:
      - rabbitmq
networks:
  rabbitmq:
